on: push
name: deploy
jobs:
  deploy:
    name: create image and pull it into register
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        push: true
        #tags: ${{ github.sha }}
        tags: jasseralg/app:latest